export const TRANSLATIONS = {
    en: {
        appName: "Sabbeh",
        appDesc: "A digital counter for your dhikr and prayers. Free Of Ads And Trackers, Made for the sake of Allah.",
        appShortDesc: "A digital counter for your dhikr and prayers.",
        settings: "Settings",
        about: "About",
        profileManagement: "Profile Management",
        exportProfile: "Export Profile",
        exportDesc: "Save your data as JSON file",
        importProfile: "Import Profile",
        importDesc: "Load data from JSON file",
        importButton: "Import",
        ok: "OK",
        resetData: "Reset App Data",
        resetDataDesc: "Clear all data and reset to default",
        confirmResetData: "This will delete all your data permanently. Are you sure?",
        resetButton: "Reset",
        github: "View Source Code on GitHub",
        reportBug: "Report a Bug",
        theme: "Theme",
        nightMode: "Night Mode",
        customColor: "Custom Color",
        rounds: "Rounds",
        count: "Count",
        reset: "Reset",
        addDhikr: "Add Dhikr",
        editDhikr: "Edit Dhikr",
        deleteDhikr: "Delete Dhikr",
        title: "Title",
        subtitle: "Subtitle",
        target: "Target",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        confirmDelete: "Are you sure you want to delete this Dhikr?",
        confirmReset: "Are you sure you want to reset the counter?",
        confirmImport: "This will replace your current dhikrs and progress. Are you sure?",
        success: "Success",
        imported: "Profile imported successfully!",
        exported: "Profile exported successfully!",
        error: "Error",
        profileNote: "Profile includes: Custom dhikrs, theme settings, dark/light mode preference, and count history for each session.",
        d_tasbih: "Tasbih", s_tasbih: "SubhanAllah",
        d_tahmid: "Tahmid", s_tahmid: "Alhamdulillah",
        d_takbir: "Takbir", s_takbir: "Allahu Akbar",
        d_istighfar: "Istighfar", s_istighfar: "Astaghfirullah",
        d_salawat: "Salawat", s_salawat: "Salawat on Prophet",
        d_tahlil: "La ilaha illallah", s_tahlil: "Tahlil",
        t_teal: "Teal", t_purple: "Purple", t_blue: "Blue", t_rose: "Rose",
        language: "Language",
        selectLanguage: "Select Language"
    },
    ar: {
        appName: "سبّح",
        appDesc: "مسبحة إلكترونية للأذكار والصلوات. مجانية وبدون إعلانات، خالصة لوجه الله.",
        appShortDesc: "مسبحة إلكترونية للأذكار والصلوات.",
        settings: "الإعدادات",
        about: "حول التطبيق",
        profileManagement: "إدارة الملف الشخصي",
        exportProfile: "تصدير البيانات",
        exportDesc: "حفظ البيانات كملف JSON",
        importProfile: "استيراد البيانات",
        importDesc: "تحميل البيانات من ملف JSON",
        importButton: "استيراد",
        ok: "حسناً",
        resetData: "إعادة ضبط البيانات",
        resetDataDesc: "مسح جميع البيانات والعودة للوضع الافتراضي",
        confirmResetData: "سيؤدي هذا إلى حذف جميع بياناتك نهائياً. هل أنت متأكد؟",
        resetButton: "إعادة ضبط",
        github: "عرض الكود المصدري على GitHub",
        reportBug: "الإبلاغ عن خطأ",
        theme: "المظهر",
        nightMode: "الوضع الليلي",
        customColor: "لون مخصص",
        rounds: "الجولات",
        count: "العدد",
        reset: "تصفير",
        addDhikr: "إضافة ذكر",
        editDhikr: "تعديل الذكر",
        deleteDhikr: "حذف الذكر",
        title: "العنوان",
        subtitle: "العنوان الفرعي",
        target: "الهدف",
        save: "حفظ",
        cancel: "إلغاء",
        delete: "حذف",
        confirmDelete: "هل أنت متأكد من حذف هذا الذكر؟",
        confirmReset: "هل أنت متأكد من تصفير العداد؟",
        confirmImport: "سيؤدي هذا إلى استبدال الأذكار والتقدم الحالي. هل أنت متأكد؟",
        success: "تم بنجاح",
        imported: "تم استيراد الملف الشخصي بنجاح!",
        exported: "تم تصدير الملف الشخصي بنجاح!",
        error: "خطأ",
        profileNote: "الملف الشخصي يتضمن: الأذكار المخصصة، إعدادات المظهر، الوضع الليلي، وسجل العداد لكل جلسة.",
        d_tasbih: "تسبيح", s_tasbih: "سبحان الله",
        d_tahmid: "تحميد", s_tahmid: "الحمد لله",
        d_takbir: "تكبير", s_takbir: "الله أكبر",
        d_istighfar: "استغفار", s_istighfar: "أستغفر الله",
        d_salawat: "صلاة على النبي", s_salawat: "اللهم صل على محمد",
        d_tahlil: "لا إله إلا الله", s_tahlil: "تهليل",
        t_teal: "فيروزي", t_purple: "بنفسجي", t_blue: "أزرق", t_rose: "وردي",
        language: "اللغة",
        selectLanguage: "اختر اللغة"
    },
    tr: {
        appName: "Sabbeh",
        appDesc: "Zikir ve dualarınız için dijital sayaç. Reklamsız ve Takipsiz, Allah rızası için yapılmıştır.",
        appShortDesc: "Zikir ve dualarınız için dijital sayaç.",
        settings: "Ayarlar",
        about: "Hakkında",
        profileManagement: "Profil Yönetimi",
        exportProfile: "Profili Dışa Aktar",
        exportDesc: "Verilerinizi JSON dosyası olarak kaydedin",
        importProfile: "Profili İçe Aktar",
        importDesc: "JSON dosyasından veri yükle",
        importButton: "İçe Aktar",
        ok: "Tamam",
        resetData: "Uygulama Verilerini Sıfırla",
        resetDataDesc: "Tüm verileri sil ve varsayılana dön",
        confirmResetData: "Bu işlem tüm verilerinizi kalıcı olarak silecektir. Emin misiniz?",
        resetButton: "Sıfırla",
        github: "Kaynak Kodunu GitHub'da Görüntüle",
        reportBug: "Hata Bildir",
        theme: "Tema",
        nightMode: "Gece Modu",
        customColor: "Özel Renk",
        rounds: "Turlar",
        count: "Sayaç",
        reset: "Sıfırla",
        addDhikr: "Zikir Ekle",
        editDhikr: "Zikri Düzenle",
        deleteDhikr: "Zikri Sil",
        title: "Başlık",
        subtitle: "Alt Başlık",
        target: "Hedef",
        save: "Kaydet",
        cancel: "İptal",
        delete: "Sil",
        confirmDelete: "Bu zikri silmek istediğinizden emin misiniz?",
        confirmReset: "Sayacı sıfırlamak istediğinizden emin misiniz?",
        confirmImport: "Bu işlem mevcut zikirlerinizi ve ilerlemenizi değiştirecektir. Emin misiniz?",
        success: "Başarılı",
        imported: "Profil başarıyla içe aktarıldı!",
        exported: "Profil başarıyla dışa aktarıldı!",
        error: "Hata",
        profileNote: "Profil şunları içerir: Özel zikirler, tema ayarları, gece modu tercihi ve her oturum için sayaç geçmişi.",
        d_tasbih: "Tesbih", s_tasbih: "SubhanAllah",
        d_tahmid: "Tahmid", s_tahmid: "Elhamdulillah",
        d_takbir: "Tekbir", s_takbir: "Allahu Ekber",
        d_istighfar: "İstiğfar", s_istighfar: "Estağfirullah",
        d_salawat: "Salavat", s_salawat: "Peygambere Salavat",
        d_tahlil: "La ilahe illallah", s_tahlil: "Tahlil",
        t_teal: "Turkuaz", t_purple: "Mor", t_blue: "Mavi", t_rose: "Gül",
        language: "Dil",
        selectLanguage: "Dil Seçin"
    },
    zh: {
        appName: "Sabbeh",
        appDesc: "用于您的 dhikr 和祈祷的数字计数器。无广告和跟踪器，为真主而制作。",
        appShortDesc: "用于您的 dhikr 和祈祷的数字计数器。",
        settings: "设置",
        about: "关于",
        profileManagement: "配置文件管理",
        exportProfile: "导出配置文件",
        exportDesc: "将您的数据保存为 JSON 文件",
        importProfile: "导入配置文件",
        importDesc: "从 JSON 文件加载数据",
        importButton: "导入",
        ok: "确定",
        resetData: "重置应用数据",
        resetDataDesc: "清除所有数据并恢复默认设置",
        confirmResetData: "这将永久删除您的所有数据。您确定吗？",
        resetButton: "重置",
        github: "在 GitHub 上查看源代码",
        reportBug: "报告错误",
        theme: "主题",
        nightMode: "夜间模式",
        customColor: "自定义颜色",
        rounds: "轮次",
        count: "计数",
        reset: "重置",
        addDhikr: "添加 Dhikr",
        editDhikr: "编辑 Dhikr",
        deleteDhikr: "删除 Dhikr",
        title: "标题",
        subtitle: "副标题",
        target: "目标",
        save: "保存",
        cancel: "取消",
        delete: "删除",
        confirmDelete: "您确定要删除此 Dhikr 吗？",
        confirmReset: "您确定要重置计数器吗？",
        confirmImport: "这将替换您当前的 dhikr 和进度。您确定吗？",
        success: "成功",
        imported: "配置文件导入成功！",
        exported: "配置文件导出成功！",
        error: "错误",
        profileNote: "配置文件包括：自定义 dhikr、主题设置、夜间模式偏好以及每个会话的计数历史记录。",
        d_tasbih: "赞颂", s_tasbih: "SubhanAllah",
        d_tahmid: "赞美", s_tahmid: "Alhamdulillah",
        d_takbir: "大赞", s_takbir: "Allahu Akbar",
        d_istighfar: "求恕", s_istighfar: "Astaghfirullah",
        d_salawat: "祝福", s_salawat: "Salawat on Prophet",
        d_tahlil: "万物非主，唯有真主", s_tahlil: "清真言",
        t_teal: "青色", t_purple: "紫色", t_blue: "蓝色", t_rose: "玫瑰色",
        language: "语言",
        selectLanguage: "选择语言"
    },
    ms: {
        appName: "Sabbeh",
        appDesc: "Kaunter digital untuk zikir dan doa anda. Percuma Tanpa Iklan Dan Penjejak, Dibuat kerana Allah.",
        appShortDesc: "Kaunter digital untuk zikir dan doa anda.",
        settings: "Tetapan",
        about: "Tentang",
        profileManagement: "Pengurusan Profil",
        exportProfile: "Eksport Profil",
        exportDesc: "Simpan data anda sebagai fail JSON",
        importProfile: "Import Profil",
        importDesc: "Muat data daripada fail JSON",
        importButton: "Import",
        ok: "OK",
        resetData: "Tetapkan Semula Data",
        resetDataDesc: "Kosongkan semua data dan tetapkan semula",
        confirmResetData: "Ini akan memadam semua data anda secara kekal. Adakah anda pasti?",
        resetButton: "Tetapkan Semula",
        github: "Lihat Kod Sumber di GitHub",
        reportBug: "Laporkan Pepijat",
        theme: "Tema",
        nightMode: "Mod Malam",
        customColor: "Warna Tersuai",
        rounds: "Pusingan",
        count: "Bilangan",
        reset: "Tetap Semula",
        addDhikr: "Tambah Zikir",
        editDhikr: "Edit Zikir",
        deleteDhikr: "Padam Zikir",
        title: "Tajuk",
        subtitle: "Subtajuk",
        target: "Sasaran",
        save: "Simpan",
        cancel: "Batal",
        delete: "Padam",
        confirmDelete: "Adakah anda pasti mahu memadamkan Zikir ini?",
        confirmReset: "Adakah anda pasti mahu menetapkan semula kaunter?",
        confirmImport: "Ini akan menggantikan zikir dan kemajuan semasa anda. Adakah anda pasti?",
        success: "Berjaya",
        imported: "Profil berjaya diimport!",
        exported: "Profil berjaya dieksport!",
        error: "Ralat",
        profileNote: "Profil merangkumi: Zikir tersuai, tetapan tema, keutamaan mod malam, dan sejarah bilangan untuk setiap sesi.",
        d_tasbih: "Tasbih", s_tasbih: "SubhanAllah",
        d_tahmid: "Tahmid", s_tahmid: "Alhamdulillah",
        d_takbir: "Takbir", s_takbir: "Allahu Akbar",
        d_istighfar: "Istighfar", s_istighfar: "Astaghfirullah",
        d_salawat: "Selawat", s_salawat: "Selawat ke atas Nabi",
        d_tahlil: "La ilaha illallah", s_tahlil: "Tahlil",
        t_teal: "Teal", t_purple: "Ungu", t_blue: "Biru", t_rose: "Merah Jambu",
        language: "Bahasa",
        selectLanguage: "Pilih Bahasa"
    },
    ur: {
        appName: "تسبیح",
        appDesc: "آپ کے ذکر اور دعاؤں کے لیے ایک ڈیجیٹل کاؤنٹر۔ اشتہارات اور ٹریکرز سے پاک، اللہ کی رضا کے لیے بنایا گیا۔",
        appShortDesc: "آپ کے ذکر اور دعاؤں کے لیے ایک ڈیجیٹل کاؤنٹر۔",
        settings: "ترتیبات",
        about: "کے بارے میں",
        profileManagement: "پروفائل کا انتظام",
        exportProfile: "پروفائل ایکسپورٹ کریں",
        exportDesc: "اپنے ڈیٹا کو JSON فائل کے طور پر محفوظ کریں",
        importProfile: "پروفائل امپورٹ کریں",
        importDesc: "JSON فائل سے ڈیٹا لوڈ کریں",
        importButton: "درآمد کریں",
        ok: "ٹھیک ہے",
        resetData: "ڈیٹا ری سیٹ کریں",
        resetDataDesc: "تمام ڈیٹا صاف کریں اور ڈیفالٹ پر واپس جائیں",
        confirmResetData: "یہ آپ کا تمام ڈیٹا مستقل طور پر حذف کر دے گا۔ کیا آپ واقعی یہ کرنا چاہتے ہیں؟",
        resetButton: "ری سیٹ کریں",
        github: "GitHub پر سورس کوڈ دیکھیں",
        reportBug: "کیڑا رپورٹ کریں",
        theme: "تھیم",
        nightMode: "نائٹ موڈ",
        customColor: "حسب ضرورت رنگ",
        rounds: "چکر",
        count: "شمار",
        reset: "ری سیٹ",
        addDhikr: "ذکر شامل کریں",
        editDhikr: "ذکر میں ترمیم کریں",
        deleteDhikr: "ذکر کو حذف کریں",
        title: "عنوان",
        subtitle: "ذیلی عنوان",
        target: "ہدف",
        save: "محفوظ کریں",
        cancel: "منسوخ کریں",
        delete: "حذف کریں",
        confirmDelete: "کیا آپ واقعی اس ذکر کو حذف کرنا چاہتے ہیں؟",
        confirmReset: "کیا آپ واقعی کاؤنٹر کو دوبارہ ترتیب دینا چاہتے ہیں؟",
        confirmImport: "اس سے آپ کے موجودہ ذکر اور پیشرفت کی جگہ لے لی جائے گی۔ کیا آپ واقعی یہ کرنا چاہتے ہیں؟",
        success: "کامیابی",
        imported: "پروفائل کامیابی کے ساتھ درآمد کیا گیا!",
        exported: "پروفائل کامیابی کے ساتھ برآمد کیا گیا!",
        error: "غلطی",
        profileNote: "پروفائل میں شامل ہیں: حسب ضرورت اذکار، تھیم کی ترتیبات، نائٹ موڈ کی ترجیح، اور ہر سیشن کے لیے شمار کی تاریخ۔",
        d_tasbih: "تسبیح", s_tasbih: "سبحان اللہ",
        d_tahmid: "تحمید", s_tahmid: "الحمد اللہ",
        d_takbir: "تکبیر", s_takbir: "اللہ اکبر",
        d_istighfar: "استغفار", s_istighfar: "استغفر اللہ",
        d_salawat: "درود", s_salawat: "نبی پر درود",
        d_tahlil: "لا الہ الا اللہ", s_tahlil: "تہلیل",
        t_teal: "ٹیل", t_purple: "جامنی", t_blue: "نیلا", t_rose: "گلابی",
        language: "زبان",
        selectLanguage: "زبان منتخب کریں"
    },
    ja: {
        appName: "Sabbeh",
        appDesc: "あなたのディクルと祈りのためのデジタルカウンター。広告やトラッカーはなく、アッラーのために作られました。",
        appShortDesc: "あなたのディクルと祈りのためのデジタルカウンター。",
        settings: "設定",
        about: "アプリについて",
        profileManagement: "プロファイル管理",
        exportProfile: "プロファイルをエクスポート",
        exportDesc: "データをJSONファイルとして保存",
        importProfile: "プロファイルをインポート",
        importDesc: "JSONファイルからデータを読み込み",
        importButton: "インポート",
        ok: "OK",
        resetData: "アプリデータをリセット",
        resetDataDesc: "すべてのデータを消去して初期状態に戻す",
        confirmResetData: "これにより、すべてのデータが完全に削除されます。よろしいですか？",
        resetButton: "リセット",
        github: "GitHubでソースコードを表示",
        reportBug: "バグを報告",
        theme: "テーマ",
        nightMode: "ナイトモード",
        customColor: "カスタムカラー",
        rounds: "ラウンド",
        count: "カウント",
        reset: "リセット",
        addDhikr: "ディクルを追加",
        editDhikr: "ディクルを編集",
        deleteDhikr: "ディクルを削除",
        title: "タイトル",
        subtitle: "サブタイトル",
        target: "目標",
        save: "保存",
        cancel: "キャンセル",
        delete: "削除",
        confirmDelete: "このディクルを削除してもよろしいですか？",
        confirmReset: "カウンターをリセットしてもよろしいですか？",
        confirmImport: "これにより、現在のディクルと進行状況が置き換えられます。よろしいですか？",
        success: "成功",
        imported: "プロファイルが正常にインポートされました！",
        exported: "プロファイルが正常にエクスポートされました！",
        error: "エラー",
        profileNote: "プロファイルには、カスタムディクル、テーマ設定、ナイトモード設定、各セッションのカウント履歴が含まれます。",
        d_tasbih: "タスビー", s_tasbih: "スブハンアッラー",
        d_tahmid: "タフミード", s_tahmid: "アルハムドゥリッラー",
        d_takbir: "タクビール", s_takbir: "アッラーフアクバル",
        d_istighfar: "イスティグファール", s_istighfar: "アスタグフィルッラー",
        d_salawat: "サラワーズ", s_salawat: "預言者への祝福",
        d_tahlil: "ラーイラーハイッラッラー", s_tahlil: "タフリール",
        t_teal: "ティール", t_purple: "紫", t_blue: "青", t_rose: "ローズ",
        language: "言語",
        selectLanguage: "言語を選択"
    }
};
